# Generated by Django 5.0 on 2024-01-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_username_qrcodelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodelist',
            options={'verbose_name': 'QR Code List', 'verbose_name_plural': 'QR Code Lists'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
