# Generated by Django 5.0.1 on 2024-02-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_group'),
    ]

    operations = [
    ]
