# Generated by Django 5.0.1 on 2024-02-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240219_1517'),
    ]

    operations = [
    ]
