# Generated by Django 5.0.1 on 2024-02-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240220_1537'),
    ]

    operations = [
    ]
