# Generated by Django 5.0.1 on 2024-02-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240220_1538'),
    ]

    operations = [
    ]
