# Generated by Django 5.0.1 on 2024-02-20 07:40

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240220_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodelist',
            name='expired_at',
            field=models.DateTimeField(default=core.models.QRCodeList.calculate_expired_at),
        ),
        migrations.AddField(
            model_name='qrcodelist',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcodelist',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 20, 7, 40, 42, 322076, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=datetime.datetime(2024, 2, 20, 7, 40, 45, 979057, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
    ]
